spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
thread:
  corePoolSize: 10
  maximumPoolSize: 50
logging:
  level:
    com.dreamcc.superdemo.mapper: debug
